// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteAppDocument(arg1) {
  return window['go']['controller']['AppDocumentController']['DeleteAppDocument'](arg1);
}
