// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {controller} from '../models';

export function DeleteAppSource(arg1:string):Promise<controller.Res>;

export function GetAppDocuments(arg1:controller.GetAppDocumentsReq):Promise<controller.Res>;

export function GetAppSourceConnectInfo(arg1:string):Promise<controller.Res>;

export function GetAppSourceList():Promise<controller.Res>;

export function ImportAppSource(arg1:controller.ImportAppSourceReq):Promise<controller.Res>;

export function LoadDocuments(arg1:string):Promise<controller.Res>;
