// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteAppSource(arg1) {
  return window['go']['controller']['AppSource']['DeleteAppSource'](arg1);
}

export function GetAppDocuments(arg1) {
  return window['go']['controller']['AppSource']['GetAppDocuments'](arg1);
}

export function GetAppSourceConnectInfo(arg1) {
  return window['go']['controller']['AppSource']['GetAppSourceConnectInfo'](arg1);
}

export function GetAppSourceList() {
  return window['go']['controller']['AppSource']['GetAppSourceList']();
}

export function ImportAppSource(arg1) {
  return window['go']['controller']['AppSource']['ImportAppSource'](arg1);
}

export function LoadDocuments(arg1) {
  return window['go']['controller']['AppSource']['LoadDocuments'](arg1);
}
