// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1) {
  return window['go']['controller']['FileController']['Greet'](arg1);
}

export function OpenFileDialog() {
  return window['go']['controller']['FileController']['OpenFileDialog']();
}

export function ReadFile(arg1) {
  return window['go']['controller']['FileController']['ReadFile'](arg1);
}

export function ReceiveFile(arg1, arg2, arg3) {
  return window['go']['controller']['FileController']['ReceiveFile'](arg1, arg2, arg3);
}

export function SaveFile(arg1) {
  return window['go']['controller']['FileController']['SaveFile'](arg1);
}
