// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {controller} from '../models';

export function Greet(arg1:string):Promise<string>;

export function OpenFileDialog():Promise<string>;

export function ReadFile(arg1:string):Promise<string>;

export function ReceiveFile(arg1:string,arg2:string,arg3:Array<number>):Promise<controller.Res>;

export function SaveFile(arg1:string):Promise<string>;
