// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BrowserOpenURL(arg1) {
  return window['go']['controller']['System']['BrowserOpenURL'](arg1);
}

export function ClipboardGetText() {
  return window['go']['controller']['System']['ClipboardGetText']();
}

export function ClipboardSetText(arg1) {
  return window['go']['controller']['System']['ClipboardSetText'](arg1);
}

export function GetOpenDir() {
  return window['go']['controller']['System']['GetOpenDir']();
}

export function GetOs() {
  return window['go']['controller']['System']['GetOs']();
}

export function OpenConfigDir() {
  return window['go']['controller']['System']['OpenConfigDir']();
}

export function ShellCMD(arg1, arg2) {
  return window['go']['controller']['System']['ShellCMD'](arg1, arg2);
}
